---
title: "Felix Jena's Resume"
author: "Felix Jena"
format: 
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: "See code"
execute: 
  warning: false
editor_options: 
  chunk_output_type: inline
---

## PERSONAL INFORMATION
**Name:** Felix Jena\
**Phone:** (385) 461 4285  
**Email:** felixjenajnr@gmail.com  
**LinkedIn:** [Felix Jena LinkedIn](https://www.linkedin.com/in/felixjenajnr)
**GitHub:** [Felix Jena GitHub](https://github.com/felixjenajnr)

## PROFILE SUMMARY
- Results-driven Analyst skilled in financial modeling, variance analysis, predictive analytics and loan covenant compliance to support strategic decision-making and risk management.
- Proficient in tools such as Excel, Powerpoint, Power BI, and SQL to generate dynamic dashboards and streamline financial reporting processes.
- Experienced in managing end-to-end data workflows, performing scenario planning, and delivering actionable insights to executive leadership.
- Adept at leveraging data-driven strategies to optimize budgeting, forecasting, and resource allocation.
- Known for collaborating cross-functionally to align financial objectives with corporate goals and delivering measurable business outcomes.

## SKILLS
- **Technical Skills:** Microsoft Excel, Power BI, Tableau, MySQL, R, SQL, SaaS financial software, Trello, Teams.
- **Financial Analysis Skills:** Budgeting, Financial Modeling, Forecasting, Data Visualization, Loan covenant compliance.
- **Soft Skills:** Leadership, Communication, Analytical Thinking, Project Management, Problem-Solving. 

## EXPERIENCE

**Data Management Intern**  
_**Maverik Inc., Salt Lake City, Utah (May 2024 - Current)**_  
- Developed and maintained a data inventory for 15 systems, improving data integrity and accuracy.
- Designed data flow diagrams and applied data validation protocols across systems to streamline interactions.
- Collaborated with technical and non-technical teams to document best practices for data management and
system integration.
- Delivered executive-level presentations showcasing project milestones and key performance metrics.

**Systems and Innovations Team Coordinator**  
_**Brigham Young University - Idaho, Rexburg, Idaho (Sep 2022 - May 2024)**_ 
- Directed branch operations, achieving a 20% growth in deposit volume and a 15% increase in lending volume.
- Analyzed client preferences, adjusted sales strategies, and improved customer loyalty by 15%.
- Reduced onboarding approval processing times by 25% through compliance coordination.
- Supervised and mentored a team of 10+, enhancing productivity through targeted training.

**Assistant Branch Manager**  
_**Capitec Bank, Pretoria, South Africa (Jun 2017 - Jul 2022)**_ 
- Directed branch operations, achieving a 20% growth in deposit volume and a 15% increase in lending volume.
- Analyzed client preferences, adjusted sales strategies, and improved customer loyalty by 15%.
- Reduced onboarding approval processing times by 25% through compliance coordination.
- Supervised and mentored a team of 10+, enhancing productivity through targeted training.

## EDUCATION
**Bachelors of Science Business Analytics**  (September 2022 - December 2024) 
Brigham Young University - Idaho, Rexburg, Idaho  
- Minor in Finance 
- Completed in under 3 years (Accelerated Program) 
- Relevant Coursework: Business Analytics, Power BI, Tableau, Excel, SQL, Advanced Financial Management,
Database Design and Development, Programming with Functions, Data Science Programming, Statistics with R.


